INSERT INTO division(id,business_unit,division_head,division_name) VALUES (1,'Admin',200,'Administration');
INSERT INTO division(id,business_unit,division_head,division_name) VALUES  (2,'Market',201,'Marketing');
INSERT INTO division(id,business_unit,division_head,division_name) VALUES  (3,'Purchasing',117,'Purchasing');
INSERT INTO division(id,business_unit,division_head,division_name) VALUES  (4,'HR',203,'Human Resources');
INSERT INTO division(id,business_unit,division_head,division_name) VALUES  (5,'Shipping',120,'Shipping');
INSERT INTO division(id,business_unit,division_head,division_name) VALUES  (6,'IT',103,'IT');
INSERT INTO division(id,business_unit,division_head,division_name) VALUES  (7,'PR',204,'Public Relations');
INSERT INTO division(id,business_unit,division_head,division_name) VALUES  (8,'Sales',176,'Sales');
INSERT INTO division(id,business_unit,division_head,division_name) VALUES  (9,'Executive',100,'Executive');
INSERT INTO division(id,business_unit,division_head,division_name) VALUES  (10,'Finance',108,'Finance');
INSERT INTO division(id,business_unit,division_head,division_name) VALUES  (11,'Accounting',206,'Accounting');


INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (100,'Steven',24000.00,NULL,9);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (101,'Neena',17000.00,100,9);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (102,'Lex',17000.00,100,9);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (103,'Alexander',9000.00,102,6);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (104,'Bruce',6000.00,103,6);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (105,'David',4800.00,103,6);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (106,'Valli',4800.00,103,6);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (107,'Diana',4200.00,103,6);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (108,'Nancy',12000.00,101,10);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (109,'Daniel',9000.00,108,10);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (110,'John',8200.00,108,10);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (111,'Ismael',7700.00,108,10);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (112,'Jose Manuel',7800.00,108,10);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (113,'Luis',6900.00,108,10);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (114,'Den',11000.00,100,3);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (115,'Alexander',3100.00,114,3);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (116,'Shelli',2900.00,114,3);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (117,'Sigal',2800.00,114,3);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (118,'Guy',2600.00,114,3);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (119,'Karen',2500.00,114,3);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (120,'Matthew',8000.00,100,5);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (121,'Adam',8200.00,100,5);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (122,'Payam',7900.00,100,5);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (123,'Shanta',6500.00,100,5);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (126,'Irene',2700.00,120,5);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (145,'John',14000.00,100,8);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (146,'Karen',13500.00,100,8);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (176,'Jonathon',8600.00,100,8);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (177,'Jack',8400.00,100,8);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (178,'Kimberely',7000.00,100,8);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (179,'Charles',6200.00,100,8);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (192,'Sarah',4000.00,123,5);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (193,'Britney',3900.00,123,5);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (200,'Jennifer',4400.00,101,1);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (201,'Michael',13000.00,100,2);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (202,'Pat',6000.00,201,2);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (203,'Susan',6500.00,101,4);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (204,'Hermann',10000.00,101,7);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (205,'Shelley',12000.00,101,11);
INSERT INTO employee(EMP_ID,employee_name,payrole_data,manager_id,division_id) VALUES (206,'William',8300.00,205,11);
